#uygulamanın server portu değişti
server:
  port: 8761

#uygulamanın hostnamesi..spring eureka starter ile eureka servera bağlanıyoruz
#eureka server ayarları
eureka:
  server:
    eviction-interval-timer-in-ms: 1000
  instance:
    hostname: ${EUREKA_SERVER_HOST:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

#zipkin bağlantı ayarları
spring:
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}/