#uygulamanın server portu değişti
server:
  port: 8503

management:
  endpoints:
    web:
      exposure:
        include: "*"

#eureka server bağlantısı..spring eureka starter ile eureka servera bağlanıyoruz
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka/

# rabbitmq ayarları yapıldı.frontendde direkt konuşababilir
spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:root}
    password: ${RABBITMQ_PASS:root}

#dinlenecek kuyruğu belirttik
  cloud:
    stream:
      bindings:
        input:
          destination: ${RABBITMQ_QUEUE_NAME:msqueue}

#zipkin bağlantı ayarları
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}/

#admin server ayarları
  boot:
    admin:
      client:
        url: http://${ADMIN_SERVER_HOST:localhost}:${ADMIN_SERVER_PORT:9000}/admin-server
        instance:
          serviceBaseUrl: http://${ADMIN_SERVER_HOST:localhost}:${ADMIN_SERVER_PORT:9000}